import { ContentItem } from './types';

export const FALLBACK_ARTICLES: ContentItem[] = [
  {
    id: "art-1",
    type: "article",
    category: "uzbekistan",
    title_uz: "O'zbekistonning yangi iqtisodiy strategiyasi: Tahlil",
    title_ru: "Новая экономическая стратегия Узбекистана: Анализ",
    title_en: "Uzbekistan's New Economic Strategy: A Strategic Analysis",
    excerpt_uz: "O'zbekiston iqtisodiyoti so'nggi yillarda jadal rivojlanish bosqichiga kirdi. Yangi iqtisodiy islohotlar doirasida modernizatsiya, investitsiya va xizmatlar sohasini rivojlantirish tahlil qilinadi.",
    excerpt_ru: "Подробный анализ основных шагов по модернизации экономики Узбекистана и ожидаемых результатов.",
    excerpt_en: "A comprehensive analysis of the core initiatives driving Uzbekistan's economic sovereignty, foreign investment flow, and long-term industrial modernization.",
    body_uz: "O'zbekiston iqtisodiyoti so'nggi yillarda jadal rivojlanish bosqichiga kirdi. Yangi strategiya doirasida xususiylashtirish jarayonlari, xorijiy investitsiyalarni jalb qilish va eksport salohiyatini oshirishga alohida e'tibor qaratilmoqda. Tahlillarga ko'ra, xususiy sektor ulushi yalpi ichki mahsulotda 75 foizga yetishi kutilmoqda. Bu esa ishsizlik darajasini kamaytirish va aholi farovonligini oshirish imkonini beradi.",
    body_ru: "Экономика Узбекистана в последние годы вступила в фазу интенсивного развития. В рамках новой стратегии особое внимание уделяется процессам приватизации, привлечению иностранных инвестиций и повышению экспортного потенциала. Согласно анализу, доля частного сектора в ВВП достигнет 75%. Это позволит существенно снизить уровень безработицы.",
    body_en: "Uzbekistan's economy has entered a phase of highly accelerated development. The current national strategy centers on bold privatization, extensive deregulation, and active attraction of foreign direct investments. Empirical projections suggest that private sector contribution to the national GDP will scale to 75% by 2028, generating a robust ecosystem of sustainable employment and public welfare.",
    author: "Directorate of Analysis",
    image_url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-06-01T12:00:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-2",
    type: "article",
    category: "uzbekistan",
    title_uz: "O'zbekiston raqamli suvereniteti va elektron hukumat taraqqiyoti",
    title_ru: "Цифровой суверенитет Узбекистана и развитие электронного правительства",
    title_en: "Digital Sovereignty and E-Government Developments in Central Asia",
    excerpt_uz: "Mamlakatning raqamli infratuzilmasini himoya qilish, kiber-xavfsizlik va davlat xizmatlarini raqamlashtirish tahlili.",
    excerpt_ru: "Анализ защиты цифровой инфраструктуры страны, кибербезопасности и цифровизации государственных услуг.",
    excerpt_en: "A strategic overview of national digital infrastructure shielding, cloud data architecture, and citizen-centric public service modernization.",
    body_uz: "Raqamli texnologiyalar davlat boshqaruvining samaradorligini oshirishda eng muhim qurol hisoblanadi. O'zbekiston kiber-xavfsizlikni kuchaytirish, milliy ma'lumotlar bazalarini himoyalash va aholiga ko'rsatiladigan elektron xizmatlarni soddalashtirish orqali o'z raqamli suverenitetini mustahkamlamoqda. Birgina My.gov.uz portali orqali ko'rsatilayotgan xizmatlar soni 500 dan oshdi.",
    body_ru: "Цифровые технологии — важнейший инструмент повышения эффективности государственного управления. Узбекистан укрепляет свой цифровой суверенитет, усиливая кибербезопасность, защищая национальные базы данных и упрощая электронные услуги. Количество услуг через My.gov.uz уже превысило 500.",
    body_en: "Digital technologies have evolved into the primary foundation for administrative efficiency. Modern reforms focus on hardening national data defense layers and launching cloud architectures to host public registries. Citizen interactions via central digital interfaces like My.gov.uz currently exceed 500 integrated endpoints, streamlining legal transactions.",
    author: "Prof. Dilshodbek Karimov",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-29T10:30:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-3",
    type: "article",
    category: "global",
    title_uz: "Markaziy Osiyoning yangi geosiyosiy muvozanati",
    title_ru: "Новый геополитический баланс Центральной Азии",
    title_en: "The Emerging Geopolitical Equilibrium in Central Asia",
    excerpt_uz: "Mintaqadagi ko'p tomonlama tashqi siyosat va global kuchlar o'rtasidagi hamkorlik istiqbollari.",
    excerpt_ru: "Многовекторная внешняя политика в регионе и перспективы сотрудничества между мировыми державами.",
    excerpt_en: "Analyzing the multivector foreign policies and diplomatic dynamics within transit corridors balancing principal global stakeholders.",
    body_uz: "Bugungi kunda Markaziy Osiyo xalqaro munosabatlarning muhim chorrahasiga aylandi. Mintaqa davlatlari o'rtasidagi integratsiya jarayonlari tashqi siyosatda yangi sahifani ochib bermoqda. Ko'p tomonlama balanslangan munosabatlar mintaqa barqarorligining asosi hisoblanadi. Shimol, janub, sharq va g'arb o'rtasidagi multimodal transport koridorlari mintaqa ahamiyatini yanada oshiradi.",
    body_ru: "Центральная Азия сегодня находится на перекрестке международных интересов. Процессы интеграции открывают новые возможности во внешней политике. Сбалансированный многовекторный диалог способствует устойчивости региона со всеми мировыми центрами силы.",
    body_en: "Central Asia is consolidating its stance as a pivotal geopolitical hub. The regional shift towards comprehensive intra-state coordination establishes a resilient front. Maintaining an independent, multivector relationship framework with adjacent continents remains essential to sustaining national sovereignty.",
    author: "Farhod Ergashev",
    image_url: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-27T08:15:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-4",
    type: "article",
    category: "speech",
    title_uz: "Millat taqdirini o'zgartirgan nutqlar diskurs-tahlili",
    title_ru: "Дискурс-анализ речей, изменивших судьбу наций",
    title_en: "Speeches That Shaped Nations: A Semantic Discourse Analysis",
    excerpt_uz: "Tarixiy va zamonaviy chiqishlar ortidagi ritorik uslublar va tinglovchini ishontirish uslublari batafsil tahlili.",
    excerpt_ru: "Анализ риторических методов, манипулятивных приемов и стратегий исторических и современных выступлений.",
    excerpt_en: "A robust critical analysis of rhetorical constructs, persuasive linguistics, and strategic framing models behind historic speeches.",
    body_uz: "Nutq — bu shunchaki so'zlar yig'indisi emas, u siyosiy iroda va g'oyaviy quroldir. Mazkur tahlilda davlat rahbarining muhim nutqlaridagi yashirin ma'nolar, ritorik savollar va tinglovchini ishontirish uslublari batafsil tekshiriladi. Siyosiy diskurs o'zgarishi natijasida ijtimoiy ongda yuz beradigan transformatsiyalar tadqiq etiladi.",
    body_ru: "Речь — это не просто набор слов, а инструмент политической воли. В данном анализе подробно исследуются скрытые смыслы, риторические вопросы и способы убеждения аудитории лидерами государств. Раскрываются лингвистические приемы общественного диалога.",
    body_en: "A state speech acts as a structured conduit for political ideology. This paper systematically decodes the subtle allegories, rhetorical questions, and target-audience engagement channels utilized in defining state directions, charting how language influences policy adoption.",
    author: "Dildora Tojiyeva",
    image_url: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-25T14:20:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-5",
    type: "article",
    category: "historical",
    title_uz: "Buyuk Ipak yo'li merosi: Siyosiy va madaniy diplomatiya darslari",
    title_ru: "Наследие Великого шелкового пути: Уроки политической и культурной дипломатии",
    title_en: "The Silk Road Legacy: Lessons in Modern Inter-State Diplomacy",
    excerpt_uz: "Tarixiy savdo aloqalarining zamonaviy geo-iqtisodiy tashabbuslar va mintaqaviy hamkorlikka ta'siri.",
    excerpt_ru: "Влияние исторических торговых связей на современные геоэкономические инициативы и региональное сотрудничество.",
    excerpt_en: "Investigating how ancient commercial corridors serve as highly functional models for contemporary trans-national partnerships and geo-economics.",
    body_uz: "Buyuk Ipak yo'li faqatgina savdo yo'li emas, balki g'oyalar, dinlar va madaniy diplomatik aloqalar almashinuv o'chog'i edi. Bugungi kunda ushby meros yangi iqtisodiy koridorlar doirasida qayta tiklanmoqda. Tarixiy aloqalar, o'zaro ishonch va do'stlik madaniyati mintaqaviy tinchlikning poydevori sifatida xizmat qiladi.",
    body_ru: "Великий шелковый путь был не только торговым маршрутом, но и колыбелью обмена идеями, религиями и культурами. Сегодня это наследие возрождается в рамках новых экономических коридоров. Уроки прошлого помогают выстраивать долгосрочное взаимовыгодное партнерство.",
    body_en: "The historical land pathways of Central Asia generated more than wealth—they fostered a durable standard for statecraft and intellectual interaction. Contemporary connectivity initiatives mirror these configurations, establishing safe conduits for regional balance.",
    author: "Dr. Jasur Alimov",
    image_url: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-22T09:00:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-6",
    type: "article",
    category: "opinion",
    title_uz: "Globallashuv va milliy o'zlikni anglash masalalari",
    title_ru: "Глобализация и вопросы национального самосознания",
    title_en: "Global Integration Dynamics vs. Sovereign Cultural Conservation",
    excerpt_uz: "Zamonaviy madaniyatlar to'qnashuvi davrida milliy urf-odatlar va qadriyatlarni asrab qolish haqida mustaqil nuqtai nazar.",
    excerpt_ru: "Независимый взгляд на сохранение национальных традиций и ценностей в эпоху столкновения современных культур.",
    excerpt_en: "An independent inquiry exploring the ongoing tension between cosmopolitan integration and local cultural institutions in modern society.",
    body_uz: "Globallashuv jarayonlari bizga cheksiz ma'lumot va imkoniyatlar berdi, lekin shu bilan birga milliy o'zlikni yo'qotish xavfini ham tug'dirdi. Milliy til, madaniyat va mafkurani tarbiyalash va yoshlar ongiga to'g'ri singdirish - kelajak asr barqarorligi uchun muhim vazifadir.",
    body_ru: "Процессы глобализации принесли бесконечный поток информации, но также создали риски для культурной уникальности. Национальные ценности, родной язык и историческая память служат главными щитами общества.",
    body_en: "Societies navigate an unprecedented flux of unified global trends. Our research documents that modern civic stability is strongly amplified when progressive global economic integration is balanced by rigorous preservation of native cultural frameworks.",
    author: "Nodira Mansurova",
    image_url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-19T11:45:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-7",
    type: "article",
    category: "speech",
    title_uz: "Siyosiy ritorika va xalqaro maydondagi imij tahlili",
    title_ru: "Политическая риторика и анализ международного имиджа",
    title_en: "The Architecture of Oratory: Political Rhetoric in Foreign Relations",
    excerpt_uz: "Xalqaro sammitlarda davlat rahbarlari nutqlarining lingvistik tahlili va uning milliy imijga ta'siri.",
    excerpt_ru: "Лингвистический анализ ключевых речей на международных саммитах и его влияние на суверенный имидж.",
    excerpt_en: "How diplomatic narratives and rhetorical framing on global platforms directly impact state soft-power indicators.",
    body_uz: "Sammitlardagi har bir so'z, metafora va imo-ishoralar puxta rejalashtiriladi. Tashqi siyosatda samarali ritorika millatning ijobiy brendini shakllantirishda bevosita rol o'ynaydi. Nutqlarda pragmatik yondashuv o'ta muhim ahamiyatga ega.",
    body_ru: "Каждое слово, метафора и жест на саммитах тщательно планируются. Эффективная внешнеполитическая риторика напрямую влияет на инвестиционную привлекательность и доверие со стороны глобального сообщества.",
    body_en: "International relations are deeply configured by soft semantics. A prime minister's selected words, pauses, and conceptual groupings at multinational forums are designed to assert leverage and construct beneficial alliances.",
    author: "Dildora Tojiyeva",
    image_url: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-16T16:00:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-8",
    type: "article",
    category: "global",
    title_uz: "Markaziy Osiyoda suv diplomatiyasi va ekologik hamkorlik",
    title_ru: "Водная дипломатия и экологическое сотрудничество в Центральной Азии",
    title_en: "Hydro-Policy and Strategic Ecological Diplomacy",
    excerpt_uz: "Amudaryo va Sirdaryo havzalarida suv resurslaridan oqilona foydalanish bo'yicha hamkorlik istiqbollari tahlili.",
    excerpt_ru: "Анализ перспектив совместного использования трансграничных водных ресурсов Амударьи и Сырдарьи.",
    excerpt_en: "Examining multi-national agreements, water conservation systems, and joint regional ecological pacts in transboundary basins.",
    body_uz: "Suv resurslari tansqiligi Markaziy Osiyo uchun eng dolzarb ekologik va geosiyosiy masalalardan biridir. Birgalikda integratsiyalashgan suv menejmenti va yashil energetika loyihalarini tatbiq etish mintaqa davlatlarining mustahkam birdamligini talab qiladi.",
    body_ru: "Дефицит пресной воды становится ключевым вызовом для нашего региона. Интегрированное управление ресурсами и внедрение водосберегающих технологий требуют коллективной стратегии и экологической солидарности.",
    body_en: "Resource division forms an indispensable pillar of regional stability. With complex hydrological variables, establishing unified, data-driven river basin networks prevents friction and guarantees mutual agricultural stability.",
    author: "Farhod Ergashev",
    image_url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-13T10:10:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-9",
    type: "article",
    category: "uzbekistan",
    title_uz: "Davlat boshqaruvida sun'iy intellekt: Istiqbollar va tavakkalchiliklar",
    title_ru: "Искусственный интеллект в госуправлении: Перспективы и риски",
    title_en: "Artificial Intelligence in Public Sphere Governance",
    excerpt_uz: "O'zbekiston davlat xizmatlarini raqamlashtirishda sun'iy intellekt modellarini tatbiq etish bo'yicha tahliliy tahrir.",
    excerpt_ru: "Аналитическое обозрение внедрения искусственного интеллекта в госслужбы и системы принятия решений.",
    excerpt_en: "A thorough review of machine learning applications, predictive algorithms, and automated workflows in modern administration.",
    body_uz: "Sun'iy intellekt davlat xizmatlari sifatini oshiradi, korrupsiyani cheklaydi va tezkor qarorlar qabul qilishga ko'maklashadi. Ammo ma'lumotlar xavfsizligi, kibertahdidlar va texnik xatolardan himoyalanish eng muhim shartlardan qolmoqda.",
    body_ru: "Алгоритмы ИИ способны оптимизировать госуслуги и искоренять коррупционные риски. При этом на передний план выходят вопросы защиты персональных данных граждан и построение устойчивых систем кибербезопасности.",
    body_en: "Integrating large language systems into public services offers unprecedented efficiency. This analysis charts data processing paradigms and transparency safeguards necessary to prevent systemic algorithmic bias.",
    author: "Prof. Dilshodbek Karimov",
    image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-10T14:50:00.000Z",
    is_admin_added: true
  },
  {
    id: "art-10",
    type: "article",
    category: "opinion",
    title_uz: "OAV bevosita jamoatchilik nazorati va ochiqlik kafolati sifatida",
    title_ru: "СМИ как инструмент общественного контроля и гарантия открытости",
    title_en: "Media Systems as Fundamental Pillars of Civic Integrity",
    excerpt_uz: "OAVning jamiyat hayotidagi o'rni, so'z erkinligi, muammolarni xolis yoritish va davlat organlari mas'uliyati.",
    excerpt_ru: "Роль прессы в современном обществе, свобода выражения мнений и подотчетность государственных органов.",
    excerpt_en: "Exploring the critical function of independent journalistic agencies in documenting development and highlighting systemic issues.",
    body_uz: "Erkin va mustaqil jamoatchilik nazorati rivojlangan davlat qurishning fundamental ustunidir. OAV jamiyatdagi tizimli muammolarni jasorat bilan ko'tarib chiqishi islohotlarning barqaror va samarali bo'lishiga zamin yaratadi.",
    body_ru: "Независимая пресса — фундамент демократического государства. Освещение острых социальных и экономических вопросов средствами массовой информации помогает вовремя реагировать на запросы граждан.",
    body_en: "The free circulation of well-researched information serves as the most responsive check on institutional transparency. Ensuring legal protection for modern investigative journalists supports balanced societal modernization.",
    author: "Nodira Mansurova",
    image_url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&q=100&w=1600",
    created_at: "2026-05-07T11:00:00.000Z",
    is_admin_added: true
  }
];
